SET(STYLE_CHECK_CPPLINT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/scripts/cpplint.py)

FUNCTION (STYLE_CHECK tgt)
  IF(SLOPPY_BUILD)
    SET(NONFATAL --nonfatal)
  ENDIF(SLOPPY_BUILD)

  IF(QUICK_BUILD)
  ELSE(QUICK_BUILD)
    ADD_CUSTOM_COMMAND(
      TARGET ${tgt}
      PRE_BUILD
      COMMAND python ${STYLE_CHECK_CPPLINT_PATH} ${NONFATAL} ${ARGN}
    )
  ENDIF(QUICK_BUILD)

ENDFUNCTION(STYLE_CHECK)

