# Add an executable target with given sources, linked to QTTesting.
FUNCTION (ADD_UNIT_TEST _name)
  ADD_EXECUTABLE(${_name} ${ARGN})

  ADD_DEFINITIONS(-DTEST_DATA_DIR="${CMAKE_CURRENT_SOURCE_DIR}")

  ADD_DEFINITIONS(${QT_DEFINITIONS})
  
  message(${QT_LIBRARIES})
  INCLUDE_DIRECTORIES(SYSTEM ${QT_QTTEST_INCLUDE_DIR})
  TARGET_LINK_LIBRARIES(${_name} ${QT_LIBRARIES} ${QT_QTTEST_LIBRARY})

  ADD_TEST(NAME ${_name} COMMAND ${_name})
ENDFUNCTION (ADD_UNIT_TEST _name)
